### ISSUE TITLE
library requirement for tetoolkit

### ISSUE THREAD

**Issue by zy041225** [mhammell-laboratory/tetoolkit#28]
Hi,

I plan to use tetoolkit to estimate TE expression in some species. However, I wonder if there's requirement in library construction step. Specifically, if the library I used is polyA-selected, would it cause some bias when estimate TEs' expression?

Best,
Yang

**Comment by olivertam** [comment]
Hi Yang,

There is a recent [publication](https://www.ncbi.nlm.nih.gov/pubmed/?term=29642008) on TCAG samples that suggest that polyA-selected libraries might not show the full profile of TE expression. Thus, it might be better to generate libraries from total RNA, rather than polyA-selected RNA.
Thanks.

Cheers,
Oliver

**Comment by zy041225** [comment]
Hi Oliver,

Thanks for confirming my guess. I'll try to find some RNA-seq data that are from total RNA.

Best,
Yang
