### ISSUE TITLE
TE gff3 to gtf?

### ISSUE THREAD

**Issue by oronoc1210** [mhammell-laboratory/tetoolkit#33]
Hello,

I'm working with Sorghum bicolor, and both my gene and TE annotation files were obtained from Phytozome as gff3 files. 
I had no trouble converting the gene gff3 file to gtf format using gffread from the cufflinks suite, but I'm having a lot more trouble converting the TE gff3 file to gtf format -- gffread just returns an empty file.

My TE gff3 file looks like this: 
[Sbicolor_313_v3.1.repeatmasked_assembly_v3.0.gff3.gz](https://github.com/mhammell-laboratory/tetoolkit/files/2416865/Sbicolor_313_v3.1.repeatmasked_assembly_v3.0.gff3.gz)
what would you recommend I do?

Thank you for your help!

**Comment by olivertam** [comment]
Hi,
To generate the TE GTF, it is easiest to make a tab-delimited file containing the following information: chromosome, start, stop, strand and TE name. If you have information regarding the TE family or class, that would be even better. You can then run the [makeTEgtf](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEToolkit/TE_GTF/makeTEgtf.pl.gz) perl script to generate the output
From your GTF file, you could remove all the lines starting with `#`, and then cut columns 1,4,5,7. You can then cut out column 9 and clean it up so that just the TE name is there, and then paste it to your other columns. You could also remove simple repeats (e.g. (AT)n and G-rich) from the annotations. You can then run `makeTEgtf.pl -c 1 -s 2 -e 3 -o 4 -n RepeatMasker -t 5 -1` on the file with the cut columns to generate the GTF file.
I generated a GTF file from your GFF3 using the method described above, and it is available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEToolkit/TE_GTF/Sbi_v3-1_rmsk_TE.gtf.gz). Please let me know if that works for you.
Thanks.

**Comment by oronoc1210** [comment]
Thanks so much for your help!
It works perfectly for me!

Best,
Conor

**Comment by Ramkynanjing** [comment]
> Hi, To generate the TE GTF, it is easiest to make a tab-delimited file containing the following information: chromosome, start, stop, strand and TE name. If you have information regarding the TE family or class, that would be even better. You can then run the [makeTEgtf](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEToolkit/TE_GTF/makeTEgtf.pl.gz) perl script to generate the output From your GTF file, you could remove all the lines starting with `#`, and then cut columns 1,4,5,7. You can then cut out column 9 and clean it up so that just the TE name is there, and then paste it to your other columns. You could also remove simple repeats (e.g. (AT)n and G-rich) from the annotations. You can then run `makeTEgtf.pl -c 1 -s 2 -e 3 -o 4 -n RepeatMasker -t 5 -1` on the file with the cut columns to generate the GTF file. I generated a GTF file from your GFF3 using the method described above, and it is available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEToolkit/TE_GTF/Sbi_v3-1_rmsk_TE.gtf.gz). Please let me know if that works for you. Thanks.

Dear Olivertam,  could you share the method generated by you,  I could not find the URL,

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software. I have updated the link to the perl script, but you can also get it [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/makeTEgtf.pl.gz).
Please don't hesitate to contact me if you have any questions about the process.

Thanks.

**Comment by Ramkynanjing** [comment]
Dear Professor Oliver Tam,


Greetings!


Thank you so for your reply. I generated TE.gtf,&nbsp; using the following script.&nbsp; &nbsp; perl makeTEgtf.pl -c 1 -s 2 -e 3 -o 4 -n RepeatMasker -t 5 -1 TEinput.txt&gt;TE.gtf.&nbsp; It is perfect,&nbsp; thank you


While running the program, TEtranscripts show this error, Please see attached screen shot images.


I need count list for TE, but I got readcount only for Gene.&nbsp;


Please send me your valuble suggestion.&nbsp;


With regards&nbsp;


Ramakrishnan












&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Oliver ***@***.***&gt;;
Date: &nbsp;Thu, Dec 2, 2021 11:41 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Muthusamy ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [mhammell-laboratory/TEtranscripts] TE gff3 to gtf? (#33)

&nbsp;



 
Hi,
 
Thank you for your interest in the software. I have updated the link to the perl script, but you can also get it here.
 Please don't hesitate to contact me if you have any questions about the process.
 
Thanks.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by olivertam** [comment]
Hi,

I cannot see the screenshot (you may have to attach it to your response on Github).
Regarding only getting gene counts but no TE counts, please ensure that the chromosome names of your TE GTF and gene GTF match (no additional `chr` in the name, for example).

Thanks.

**Comment by Ramkynanjing** [comment]
Dear Professor Oliver Tam,


Thank you so for your quick reply. I am so sorry,&nbsp;&nbsp;


In this mail, I have attached a PPT file, in which I have pasted the screen shot images.&nbsp;


I also shown the screen shot images of TE GTF and gene GTF.&nbsp;


I think the chromosome name is correct.&nbsp;


Please send me your valuble suggestion.


With regards


Ramakrishnan

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Oliver ***@***.***&gt;;
Date: &nbsp;Fri, Dec 3, 2021 11:06 AM
To: ***@***.***&gt;; 
Cc: &nbsp;"Muthusamy ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [mhammell-laboratory/TEtranscripts] TE gff3 to gtf? (#33)

&nbsp;



 
Hi,
 
I cannot see the screenshot (you may have to attach it to your response on Github).
 Regarding only getting gene counts but no TE counts, please ensure that the chromosome names of your TE GTF and gene GTF match (no additional chr in the name, for example).
 
Thanks.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by olivertam** [comment]
HI Ramakrishnan,

I'm afraid that none of the attachments will work if you respond via email.  You will need to respond on Github itself.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Professor Oliver Tam,

Thank you for your quick reply. While running the program, transcripts show some errors, 
I have pasted the screenshot images, I need a count list for TE, but I got a read count only for Gene;
I also showed the screenshot images of TE GTF and gene GTF;
Please send me your valuable suggestion.
With regards
Ramakrishnan

![image](https://user-images.githubusercontent.com/70749594/144541234-906d5cb0-9cc1-4f83-9caa-24f0a4352c5b.png)

![image](https://user-images.githubusercontent.com/70749594/144541258-ebaf857c-fd2c-40ff-aa5d-9911f3ee7f23.png)

![image](https://user-images.githubusercontent.com/70749594/144541387-ab0df69f-5926-4e46-bb0c-c706687f7caf.png)
![image](https://user-images.githubusercontent.com/70749594/144541435-6310e89f-9eae-497c-ba03-f8c5cb73c7da.png)

**Comment by olivertam** [comment]
Hi Ramakrishnan,

The "errors" are warning messages from the `pysam` module, and has no impact on `TEtranscripts` (see #82).

Looking at your TE GTF file, it appears the `gene_id` for all entries is `RepeatMasker`. They should instead correspond to the TE name. You might need to check the `TEinput.txt` file to ensure that the TE name is in the correct column.

It is also unusual that you had zero non-uniquely mapped reads in your BAM file. It is unclear what alignment parameters you are using, but given that many TE are repetitive elements in the genome, it is typically recommended to allow non-uniquely mapped reads when aligning (we typically allow up to 100 genomic alignments).

Hope this is helpful. Please feel free to let me know if you have further questions.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Professor Oliver Tam, 

Many thanks for your response.  I will recheck the TE.gtf file, and update you. 

with regards 

Ramky

**Comment by olivertam** [comment]
Hi Ramky,

If you look at column 6 (attributes), you will find information such as repeat name, class etc... You will need to parse out the information to have those info as separate columns, and then run the `makeTEgtf.pl` script with the correct columns for the various pieces of information.

Hope that is helpful. If you still have issues, you can provide the GFF3 file, and we can convert it to the TE GTF.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,  

Many thanks for your kind response.  Could I send you GFF3 personally, 

with regards

**Comment by olivertam** [comment]
Hi,

Feel free to send the GFF3 to tam at cshl dot edu, or attach it on Github.

Thanks.

**Comment by olivertam** [comment]
Hi,

I have sent you the download links for the files, but I wanted to also note down the steps that were used to generate it.
1) Convert GFF into tab-separated file containing relevant info in various columns:
```
$ head -n 4 TE.gff
##gff-version 3
PH01000409      RepeatMasker    disperseRepeat  1       1130    9321    +       .       ID=repeat_TE0000001;Target=Repeat_8240 948 2073;Class=ClassII/TIR/CACTA;PercDiv=4.8;PercDel=0.3;PercIns=0.6;
PH01000409      RepeatMasker    disperseRepeat  913     1163    850     -       .       ID=repeat_TE0000002;Target=Repeat_14470 4640 4882;Class=ClassI/LINE/L1;PercDiv=15.2;PercDel=7.2;PercIns=10.7;
PH01000409      RepeatMasker    disperseRepeat  1130    1315    1235    +       .       ID=repeat_TE0000003;Target=Repeat_24486 6739 6927;Class=ClassI/LTR/Copia;PercDiv=13.4;PercDel=1.6;PercIns=0.0;
```
```
$ sed '/^#/d;s/;/  /g;s/[A-Za-z]*=//g;s/ / /g;s/\//:/;s/\//        /;s/?/Unknown/g' TE.gff | awk -F "      " -v OFS="      " 'NF==18;NF<18{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13,$14,$15,$16,$17}' > TE_input.txt
```
Note: All gaps in the code above are tabs

```
$ head -n 3 TEinput.txt
PH01000409      RepeatMasker    disperseRepeat  1       1130    9321    +       .       repeat_TE0000001        Repeat_8240     948     2073    ClassII:TIR     CACTA   4.8     0.3     0.6     
PH01000409      RepeatMasker    disperseRepeat  913     1163    850     -       .       repeat_TE0000002        Repeat_14470    4640    4882    ClassI:LINE     L1      15.2    7.2     10.7    
PH01000409      RepeatMasker    disperseRepeat  1130    1315    1235    +       .       repeat_TE0000003        Repeat_24486    6739    6927    ClassI:LTR      Copia   13.4    1.6     0.0     
```

2) Generate TE GTF
```
$ perl makeTEgtf.pl -c 1 -s 4 -e 5 -o 7 -t 10 -n RepeatMasker -f 14 -C 13 -S 6 -1 TE_input.txt > TE.gtf
$ head -n 3 TE.gtf
PH01000409      RepeatMasker    exon    1       1130    9321    +       .       gene_id "Repeat_8240"; transcript_id "Repeat_8240"; family_id "CACTA"; class_id "ClassII:TIR";
PH01000409      RepeatMasker    exon    913     1163    850     -       .       gene_id "Repeat_14470"; transcript_id "Repeat_14470"; family_id "L1"; class_id "ClassI:LINE";
PH01000409      RepeatMasker    exon    1130    1315    1235    +       .       gene_id "Repeat_24486"; transcript_id "Repeat_24486"; family_id "Copia"; class_id "ClassI:LTR";
```

Please let me know if there are any issues or further questions.

Thanks.

**Comment by Ramkynanjing** [comment]
Dear Oliver Tam,&nbsp;

Thank you so much for spending your valuble time in generating TE GTF file.&nbsp;

It is very clear and more useful to my research group.&nbsp;

with regards&nbsp;

Ramky




&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Oliver ***@***.***&gt;;
Date: &nbsp;Fri, Dec 3, 2021 08:39 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Muthusamy ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [mhammell-laboratory/TEtranscripts] TE gff3 to gtf? (#33)

&nbsp;



 
Hi,
 
I have sent you the download links for the files, but I wanted to also note down the steps that were used to generate it.
  
Convert GFF into tab-separated file containing relevant info in various columns:
  $ head -n 4 TE.gff ##gff-version 3 PH01000409      RepeatMasker    disperseRepeat  1       1130    9321    +       .       ID=repeat_TE0000001;Target=Repeat_8240 948 2073;Class=ClassII/TIR/CACTA;PercDiv=4.8;PercDel=0.3;PercIns=0.6; PH01000409      RepeatMasker    disperseRepeat  913     1163    850     -       .       ID=repeat_TE0000002;Target=Repeat_14470 4640 4882;Class=ClassI/LINE/L1;PercDiv=15.2;PercDel=7.2;PercIns=10.7; PH01000409      RepeatMasker    disperseRepeat  1130    1315    1235    +       .       ID=repeat_TE0000003;Target=Repeat_24486 6739 6927;Class=ClassI/LTR/Copia;PercDiv=13.4;PercDel=1.6;PercIns=0.0;  $ sed '/^#/d;s/;/  /g;s/[A-Za-z]*=//g;s/ / /g;s/\//:/;s/\//        /;s/?/Unknown/g' TE.gff | awk -F "      " -v OFS="      " 'NF==18;NF<18{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13,$14,$15,$16,$17}' &gt; TE_input.txt  
Note: All gaps in the code above are tabs
 $ head -n 3 TEinput.txt PH01000409      RepeatMasker    disperseRepeat  1       1130    9321    +       .       repeat_TE0000001        Repeat_8240     948     2073    ClassII:TIR     CACTA   4.8     0.3     0.6      PH01000409      RepeatMasker    disperseRepeat  913     1163    850     -       .       repeat_TE0000002        Repeat_14470    4640    4882    ClassI:LINE     L1      15.2    7.2     10.7     PH01000409      RepeatMasker    disperseRepeat  1130    1315    1235    +       .       repeat_TE0000003        Repeat_24486    6739    6927    ClassI:LTR      Copia   13.4    1.6     0.0        
Generate TE GTF
  $ perl makeTEgtf.pl -c 1 -s 4 -e 5 -o 7 -t 10 -n RepeatMasker -f 14 -C 13 -S 6 -1 TE_input.txt &gt; TE.gtf $ head -n 3 TE.gtf PH01000409      RepeatMasker    exon    1       1130    9321    +       .       gene_id "Repeat_8240"; transcript_id "Repeat_8240"; family_id "CACTA"; class_id "ClassII:TIR"; PH01000409      RepeatMasker    exon    913     1163    850     -       .       gene_id "Repeat_14470"; transcript_id "Repeat_14470"; family_id "L1"; class_id "ClassI:LINE"; PH01000409      RepeatMasker    exon    1130    1315    1235    +       .       gene_id "Repeat_24486"; transcript_id "Repeat_24486"; family_id "Copia"; class_id "ClassI:LTR";  
Please let me know if there are any issues or further questions.
 
Thanks.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,

Thank you very much for your kind response and your clear explanation.

This is really very clear and useful to me. 

with regards

Ramky

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,

As per your suggestion "As part of the --sortByPos parameter, TEcount is resorting the file by name (using samtools). It then tries to load the file (which is a hidden file in the same folder) for processing. I'm assuming that you have sufficient space on your system, but that's worth checking. One option is to resort the BAM file by read name (samtools sort -n ...), and then run TEcount without the --sortByPos parameter" 

I run the TEtranscripts, but I got warning message, 

As you mentiond "The "errors" are warning messages from the pysam module, and has no impact on TEtranscripts (see #82)."

Shall I ignore this "warning messages"?

![image](https://user-images.githubusercontent.com/70749594/144623216-52abad73-2ed2-4c99-a32a-6451cab11e99.png)

**Comment by olivertam** [comment]
Hi Ramky,

Yes, you can safely ignore those warning messages that you highlighted.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

Thank you very much for your kind response.

with regards

Ramky

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, Greetings!
I want to treat each copy of the TE as a distinct “gene”.  Using R program, I merged ID with repeat name and generated TE.GTF.  But output of the TE. GTF is not in the correct format. 
I also learned that although the input file is in text format, but the text file should be in the GFF3 file format; it should not in the random format. 
In the R program, I subset only required information, “Chrom column, start column, stop column, strand column, source, TE name, family column, class column”. After strand column, “dot column” this is also important. 
After so many attempts, I generated GTF, but I want to add underscore (_) between ID and repeat name. 
I feel it will be better, if I use concatenate function in Linux. Could you show me one examples how to use concatenate function and how to add underscore (_) between ID and repeat name  in Linux? 
![image](https://user-images.githubusercontent.com/70749594/144782661-b85283fb-8efa-449c-a39f-d2f992638485.png)

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, Greetings!
What is the minimum system requirement to run TEtranscripts?
I use WSL2 (windows subsystem for Linux), and my computer has 128 GB RAM. 
When I consider repeat name as gene, it took 3 hours to run 2 BAM files each with 10 GB size. 
However, while treating each copy of the TE as a distinct “gene”, TEtranscripts is taking long time, now 24 hours over, still it is running, I do not know how long it will take. 
Could you give me some suggestion? 

![image](https://user-images.githubusercontent.com/70749594/144783799-85eca1b5-9464-43af-acb0-da0e6ae68a5d.png)

With regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,

Millions of thanks to you for your kind response and sending me the example.

The program is also completed, It took more 36 hours.  

![image](https://user-images.githubusercontent.com/70749594/144868782-c602cc5f-efaf-45a2-90ad-35f8ca7e1d99.png)



with regards

Ramky

**Comment by olivertam** [comment]
Thank you for the update.
As you can see from the logs, the creation of the TE index took the longest amount of time. This is part of the rationale of using pre-built indices for `TElocal`

All the best.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,

Many thanks for the information. I will try TElocal.

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Thank you so much for your kind reply.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,

Thank you for providing very useful software. TEtranscripts and TElocal are the same,  but, in order to run TElocal,  we have to provide,  indexed GTF files. 

Could you show me some example how to generate this file,  I do not have any ideas about this. 

I can also use TEcount instead of TEtranscripts,  and generate only count table alone that can be used for differential analysis. 

the only difference is that TEtrnscripts will peroform differentiall analsis, 

TElocal use indexed GTF file. 

with regards 

Ramky


![image](https://user-images.githubusercontent.com/70749594/144968136-b7face20-9f8d-499e-850f-3deb2af8e7d7.png)

**Comment by olivertam** [comment]
Hi,

I transferred your question to our `TElocal` repository. You can find it [here](https://github.com/mhammell-laboratory/TElocal/issues/18).

Thanks

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

As per your suggestion,  I run the following script, but the program is running like this, 

did you modify the Perl script,  you asked me to run makeTEgtf_v2.pl,  I do not have this,  

please send me your suggestion.



![image](https://user-images.githubusercontent.com/70749594/145141865-1e0ab1e2-69a7-4e88-8ba4-568da88c1eb0.png)
  

with regards 

Ramky

**Comment by olivertam** [comment]
Hi Ramky,

If you are running `TElocal`, you do not need to make a unique ID GTF file.
Please check that your file is tab-delimited/separated, and not space separated.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

Many thanks, yes my files are not tab-delimited,  

to run,  TElocal, can I use the same GTF that you showed me.  

![image](https://user-images.githubusercontent.com/70749594/145143987-87b1215c-1930-423f-93e1-e0ff8e0b4bdc.png)





![image](https://user-images.githubusercontent.com/70749594/145143768-d8c324d7-6bc1-4239-a7f7-0fad2d4f8695.png)
with regards 

Ramky

**Comment by olivertam** [comment]
Hi Ramky,

Please use the original GTF for building the `TElocal` index.
Regarding your error, please ensure that you are not copying and pasting the command line, but attempt to type it out. There could be formatting errors that are introduced.
If that does not resolve the issue, we can generate the file for you.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,  

I do not know why Tab key function is not working in my WSL2.  So,  I used the following script,  

awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9 "_" $10"\t"$11"\t"$12"\t"$13"\t"$14"\t"$15"\t"$16"\t"$17"\t"}' TE_input.txt > TE_input2.txt   

 (Is it correct?)

and run makeTEgtf.pl    

I am sorry, I could not understand this,    according to my understanding, two kinds of analysis: 

1. We can treat each copy as a distinct gene,  or  2. we can treat all the same copies as a single gene,  

For example,  in TE.gtf,   Repeat_8240 is present 361 times, (total copy number).  we can treat all copies as a single gene or we can treat each copy as a distinct gene

could you explain to me,  what is locus-specific, TElocal is locus-specific analysis. 

![image](https://user-images.githubusercontent.com/70749594/145178474-26e6f8d0-22cb-4a9e-bf22-11f5c79d5d69.png)

With regards 

Ramky

**Comment by olivertam** [comment]
Hi Ramky,

If you are trying to insert a tab on the Linux command line, you will need to do the following combination: `ctrl-V`, then `tab`. That should hopefully work.
To answer your question: the way that RepeatMasker works is that it takes a set of TE consensus sequences, and then identify genomic regions that matches the consensus. When we treat "all copies of the same TE as a single gene", it means that we aggregate counts for all identified copies of the TE consensus in the genome as belonging to that TE consensus (which we sometimes designated as 'sub-famiily'). 
For a locus-specific analysis, each copy will be given its own count (rather than aggregated to the identified consensus), and so you will get values for each TE copy (which we sometimes designate as 'instance'). So in your example, each copy (361) of the Repeat_8240 will have a count (rather than an aggregated count).
Just a reminder, `TElocal` uses the original GTF (your `TE.gtf`) and not the modified one (`TE2.gtf`) to build the index.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

Thank you for your kind explanation and guidance.  

with regards

Ramky

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

I think TEtranscripts also provides Locus-level TE RNA quantification.

am I correct?   I think locus-level is each of copy TE

with regards

![image](https://user-images.githubusercontent.com/70749594/148631351-2a488d03-f38b-4ce6-bff5-d57a2c86fe4d.png)

**Comment by olivertam** [comment]
Hi,

`TEtranscripts` was not designed for locus/copy level quantification, and thus not typically utilized this way. `TElocal` is our locus-level implementation.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

thank you, again I am confused with my GTF file.  Now,  I have two kinds of GTFs file. 

![image](https://user-images.githubusercontent.com/70749594/148631820-f595459b-90bb-46ba-a0e7-288b008fe446.png)
![image](https://user-images.githubusercontent.com/70749594/148631889-1633b921-5280-41ed-9370-ff6073114e5b.png)

**Comment by olivertam** [comment]
One of your GTF file (`TE.gtf`) uses the repeat type/subfamily as the `gene_id`, while the other (`TE2.gtf`) used the TE copy name as the `gene_id`. The former is what `TEtranscripts` typically expects, whereas the other one was a "hack" to make `TEtranscripts` do locus-level quantification. The "hack" has now been replaced by `TElocal`

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,  

Thank you so much. This is  results of TE2.gtf. 

The repeat_8240 is present more than 300 times. if  I use TE.gtf,  I will get only count value for repeat_8240 by combining all 300 counts into single count because it uses the repeat type/subfamily as the gene_id. 

Whereas If I use TE2.gtf, I will get read count for each epeat_8240, because in TE2.gtf, each epeat_8240 is treated as gene ID because of this "repeat_TE0004914".  

Is it correct?

with regards


![image](https://user-images.githubusercontent.com/70749594/148632111-a9e9ac23-9dbc-4af7-83e1-c42840d6d839.png)

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,

I use TElocal,  I have to use TE.gtf,  not TE2.gtf. 

is it correct.

with regards 

Ramky

**Comment by olivertam** [comment]
Hi,

Yes, you are correct regarding the difference between `TE.gtf` and `TE2.gtf`.
`TElocal` is designed to work with `TE.gtf` to mimic `TE2.gtf` (which is a "hack" for`TEtranscripts`).

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,
Thank you.
Ramky

**Comment by 666lixiaona** [comment]
who can provide BAM profile and GTF profile for gene and TE?thank you very much

**Comment by olivertam** [comment]
Hi,

Are you asking for where you can get the input files?
You generate the BAM from aligning your reads against the genome build of choice. We typically use STAR, and allow up to 100 mismatches (though that's based on mammalian genomes).
For gene GTF, you can get them from [UCSC](https://genome.ucsc.edu/), [Ensembl](https://useast.ensembl.org/index.html) or [GENCODE](https://www.gencodegenes.org/), though that could possibly change the genome build that you're using (i.e. you want to use the FASTA with the same chromosome nomenclature as your GTF source).
For TE GTF, you can get them [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/), and for certain species, you would need to get the corresponding GTF based on the source of your FASTA and GTF (e.g. hg38 for UCSC, GRCh38_Ensembl for Ensembl, GRCh38_GENCODE for GENCODE).

Thanks.

**Comment by olivertam** [comment]
Hi,

If you want some test data, they are available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/test_data/)
For usage information, feel free to read our [README](https://github.com/mhammell-laboratory/TEtranscripts/blob/master/README.rst). For the description of our algorithm, you can read the corresponding [publication[(https://pubmed.ncbi.nlm.nih.gov/26206304/)

Please let me know if you have other questions.

Thanks.

**Comment by 666lixiaona** [comment]
HI,

Thank you very much.I will deeply study it.
Another question is how you understand the subfamily of TE?How to distinguish superfamily and subfamily of TE? What are their styles(or features) for subfamily of TE?

Thanks.

**Comment by 666lixiaona** [comment]
Ok,I get it.Thank you very much.

**Comment by 666lixiaona** [comment]
Hi,

I want to ask you how the EM algorithum is applied in TEtranscripts.What is the hidden variable?Can you provide a specific process 
to help me understand?

Thanks.

**Comment by olivertam** [comment]
Hi,

You should be able to find the full details in the [paper](https://pubmed.ncbi.nlm.nih.gov/26206304/).

Thanks.
