### ISSUE TITLE
Can not run TEtranscripts with test files.

### ISSUE THREAD

**Issue by jdaron** [mhammell-laboratory/tetoolkit#4]
Hello, 

I am contacting you because I just install TEtranscripts and all the dependency to my computer, and I was unsuccessful to launch TEtranscripts with the test files you are providing. 

Here is the error message I got: 
INFO  @ Wed, 02 Dec 2015 18:20:21: Finished processing sample files 
INFO  @ Wed, 02 Dec 2015 18:20:21: Generating counts table 
CRITICAL @ Wed, 02 Dec 2015 18:20:21: Error in running differential analysis!
 
CRITICAL @ Wed, 02 Dec 2015 18:20:21: Error: [Errno 13] Permission denied
 
CRITICAL @ Wed, 02 Dec 2015 18:20:21: [Exception type: OSError, raised in subprocess.py:1335]

Here if the commend line I am launching:
$ TEtranscripts --sortByPos --mode multi --TE dm3_rmsk_TE.gtf --GTF dm3_refGene.gtf --project singleEnd_test -t test_data_SE_treatment.bam -c test_data_SE_control.bam 2> log 

To provide you information on my environment I I install pysam correctly :
$ pip install pysam
Requirement already satisfied (use --upgrade to upgrade): pysam in /Users/daron.6/Library/Python/3.4/lib/python/site-packages
Requirement already satisfied (use --upgrade to upgrade): cython>=0.20.1 in /Users/daron.6/Library/Python/3.4/lib/python/site-packages (from pysam)

And I install DESeq using the following command:
source("http://www.bioconductor.org/biocLite.R")
biocLite("DESeq")

Thanks for helping me to figure out a way to make the program working.
Josquin

**Comment by status-five** [comment]
Subject:
FW: problem when running TEtranscripts with test files
From:
"Jin, Ying" <yjin@cshl.edu>
Date:
12/3/15, 4:15 PM
To:
"Molik, David" <dmolik@cshl.edu>, "Tam, Oliver" <tam@cshl.edu>

FYI.

Ying Jin PhD

Bioinformatics Shared Resources
Cold Spring Harbor Lab
516-367-5190
yjin at cshl dot edu
From: Daron, Josquin M. [daron.6@osu.edu]
Sent: Thursday, December 03, 2015 3:49 PM
To: Jin, Ying
Subject: Re: problem when running TEtranscripts with test files

Hi Thanks a lot for your quick answer, 

So I do have the correct ***.cntTabe and ***.R. I run the Rscript in a R session and it seams that everything goes well. I got 2 file singleEnd_test_gene_TE_analysis.txt and singleEnd_test_sigdiff_gene_TE.txt.
I think the problem is in my imac I only have a R.app, which I am using with Rstudio. But I don’t access to this R.app in the terminal, and they is no R in my usr/bin/. 
So I create a symbolic link between where is located Rscript in my computer and my bin, and it works:
Here is the cmd: ln -s  /Library/Frameworks/R.framework/Resources/bin/Rscript ~/bioInf/bin/.

Thanks for your help, it was really useful.
Best, 
Josquin

**Comment by status-five** [comment]
Marking Resolved.

**Comment by Lipingliao** [comment]
I got the same issue, thanks for sharing
